### ISSUE TITLE
Exporting other resource types than Images from Salsah

### ISSUE THREAD

**Issue by julsraemy** [Participatory-Image-Archives/pia-data-model#4]
Exporting the metadata of the following resource types (whole of the SGV, not only the PIA Collections):

- [x] sgv:Subject
- [x] sgv:Persons
- [x] sgv:Film
- [x] sgv:Sequence
- [x] sgv:Tonbildschau
- [x] sgv:Album
- [x] sgv:Collection

**Comment by julsraemy** [comment]
I couldn't create the CSV file for `sgv:Subject` and `sgv:Sequence`. The unresolved and resolved XML files have been downloaded though:
-  https://github.com/Participatory-Image-Archives/pia-data-model/tree/main/salsah-export/Subject
- https://github.com/Participatory-Image-Archives/pia-data-model/tree/main/salsah-export/Sequence

_Update: As @thgie will most likely use the unresolved XML files to populate the PIA Database, it's not a big deal._

**Comment by julsraemy** [comment]
I've just noticed that the `sgv:Persons` metadata are not exhaustive. We have only 999 items. Here is the error I got: 

```
Traceback (most recent call last):
  File "/Users/julienraemy/Documents/GitHub/salsah-export/salsah2xml.py", line 1274, in <module>
    main()
  File "/Users/julienraemy/Documents/GitHub/salsah-export/salsah2xml.py", line 1270, in main
    program()
  File "/Users/julienraemy/Documents/GitHub/salsah-export/salsah2xml.py", line 1263, in program
    con.process_resource(resource, images_path, download, args.request_image_type, write_metadata, verbose)
  File "/Users/julienraemy/Documents/GitHub/salsah-export/salsah2xml.py", line 1117, in process_resource
    propnode = self.process_property(propname, resource["props"][propname], verbose)  # process_property()
  File "/Users/julienraemy/Documents/GitHub/salsah-export/salsah2xml.py", line 1060, in process_property
    valnode = self.process_value(int(prop["valuetype_id"]), value, verbose)
  File "/Users/julienraemy/Documents/GitHub/salsah-export/salsah2xml.py", line 904, in process_value
    encoding, valele.text = process_richtext(
  File "/Users/julienraemy/Documents/GitHub/salsah-export/salsah2xml.py", line 134, in process_richtext
    attributes = json.loads(textattr)
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 20 (char 19)
```
